// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/lead/lead.proto

package leadv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeadStatus int32

const (
	LeadStatus_UNKNOWN             LeadStatus = 0
	LeadStatus_PENDING             LeadStatus = 1
	LeadStatus_FINISHED            LeadStatus = 2
	LeadStatus_ERROR               LeadStatus = 3
	LeadStatus_FINISHED_WITH_ERROR LeadStatus = 4
)

// Enum value maps for LeadStatus.
var (
	LeadStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "FINISHED",
		3: "ERROR",
		4: "FINISHED_WITH_ERROR",
	}
	LeadStatus_value = map[string]int32{
		"UNKNOWN":             0,
		"PENDING":             1,
		"FINISHED":            2,
		"ERROR":               3,
		"FINISHED_WITH_ERROR": 4,
	}
)

func (x LeadStatus) Enum() *LeadStatus {
	p := new(LeadStatus)
	*p = x
	return p
}

func (x LeadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lead_lead_proto_enumTypes[0].Descriptor()
}

func (LeadStatus) Type() protoreflect.EnumType {
	return &file_proto_lead_lead_proto_enumTypes[0]
}

func (x LeadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeadStatus.Descriptor instead.
func (LeadStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_lead_lead_proto_rawDescGZIP(), []int{0}
}

type Classification int32

const (
	Classification_UNKNOWN_CLASSIFICATION Classification = 0
	Classification_VIOLENT                Classification = 1
	Classification_BUSSINES               Classification = 2
	Classification_MISCELLANIOUS          Classification = 3
	Classification_PEOPLE                 Classification = 4
	Classification_INDUSTRY               Classification = 5
	Classification_EMOTIONAL              Classification = 6
	Classification_CRIMINAL               Classification = 7
)

// Enum value maps for Classification.
var (
	Classification_name = map[int32]string{
		0: "UNKNOWN_CLASSIFICATION",
		1: "VIOLENT",
		2: "BUSSINES",
		3: "MISCELLANIOUS",
		4: "PEOPLE",
		5: "INDUSTRY",
		6: "EMOTIONAL",
		7: "CRIMINAL",
	}
	Classification_value = map[string]int32{
		"UNKNOWN_CLASSIFICATION": 0,
		"VIOLENT":                1,
		"BUSSINES":               2,
		"MISCELLANIOUS":          3,
		"PEOPLE":                 4,
		"INDUSTRY":               5,
		"EMOTIONAL":              6,
		"CRIMINAL":               7,
	}
)

func (x Classification) Enum() *Classification {
	p := new(Classification)
	*p = x
	return p
}

func (x Classification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Classification) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lead_lead_proto_enumTypes[1].Descriptor()
}

func (Classification) Type() protoreflect.EnumType {
	return &file_proto_lead_lead_proto_enumTypes[1]
}

func (x Classification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Classification.Descriptor instead.
func (Classification) EnumDescriptor() ([]byte, []int) {
	return file_proto_lead_lead_proto_rawDescGZIP(), []int{1}
}

// Lead model
type Lead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id" bson:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: json:"search_id" bson:"search_id"
	SearchID string `protobuf:"bytes,2,opt,name=searchID,proto3" json:"searchID,omitempty"`
	// @inject_tag json:"subject_full_name" bson:"subject_full_name"
	SubjectFullName string `protobuf:"bytes,3,opt,name=subjectFullName,proto3" json:"subjectFullName,omitempty"`
	// @inject_tag json:"classification" bson:"classification"
	Classification Classification `protobuf:"varint,4,opt,name=Classification,proto3,enum=lead.Classification" json:"Classification,omitempty"`
	// @inject_tag json:"content" bson:"content"
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	// @inject_tag json:"key_content" bson:"key_content"
	KeyContent []string `protobuf:"bytes,6,rep,name=keyContent,proto3" json:"keyContent,omitempty"`
	// @inject_tag json:"created_at" bson:"created_at"
	CreatedAt string `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// @inject_tag json:"updated_at" bson:"updated_at"
	UpdatedAt string `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	// @inject_tag: json:"source" bson:"source"
	Source string `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *Lead) Reset() {
	*x = Lead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lead_lead_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lead) ProtoMessage() {}

func (x *Lead) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_lead_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lead.ProtoReflect.Descriptor instead.
func (*Lead) Descriptor() ([]byte, []int) {
	return file_proto_lead_lead_proto_rawDescGZIP(), []int{0}
}

func (x *Lead) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lead) GetSearchID() string {
	if x != nil {
		return x.SearchID
	}
	return ""
}

func (x *Lead) GetSubjectFullName() string {
	if x != nil {
		return x.SubjectFullName
	}
	return ""
}

func (x *Lead) GetClassification() Classification {
	if x != nil {
		return x.Classification
	}
	return Classification_UNKNOWN_CLASSIFICATION
}

func (x *Lead) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Lead) GetKeyContent() []string {
	if x != nil {
		return x.KeyContent
	}
	return nil
}

func (x *Lead) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Lead) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Lead) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// LeadView model
type LeadView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"led_id" bson:"led_id"
	LedId string `protobuf:"bytes,1,opt,name=led_id,json=ledId,proto3" json:"led_id,omitempty"`
	// @inject_tag: json:"subject_name" bson:"subject_name"
	SubjectName string `protobuf:"bytes,2,opt,name=subject_name,json=subjectName,proto3" json:"subject_name,omitempty"`
	// @inject_tag: json:"lead_status" bson:"lead_status"
	LeadStatus string `protobuf:"bytes,3,opt,name=lead_status,json=leadStatus,proto3" json:"lead_status,omitempty"`
}

func (x *LeadView) Reset() {
	*x = LeadView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lead_lead_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeadView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadView) ProtoMessage() {}

func (x *LeadView) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_lead_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadView.ProtoReflect.Descriptor instead.
func (*LeadView) Descriptor() ([]byte, []int) {
	return file_proto_lead_lead_proto_rawDescGZIP(), []int{1}
}

func (x *LeadView) GetLedId() string {
	if x != nil {
		return x.LedId
	}
	return ""
}

func (x *LeadView) GetSubjectName() string {
	if x != nil {
		return x.SubjectName
	}
	return ""
}

func (x *LeadView) GetLeadStatus() string {
	if x != nil {
		return x.LeadStatus
	}
	return ""
}

var File_proto_lead_lead_proto protoreflect.FileDescriptor

var file_proto_lead_lead_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x65, 0x61, 0x64, 0x2f, 0x6c, 0x65, 0x61,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x65, 0x61, 0x64, 0x22, 0xa8, 0x02,
	0x0a, 0x04, 0x4c, 0x65, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x75, 0x6c,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0e,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x2e, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6b, 0x65, 0x79, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x65, 0x0a, 0x08, 0x4c, 0x65, 0x61, 0x64,
	0x56, 0x69, 0x65, 0x77, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x64, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a,
	0x58, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45,
	0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x4e, 0x49, 0x53,
	0x48, 0x45, 0x44, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03,
	0x12, 0x17, 0x0a, 0x13, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x5f, 0x57, 0x49, 0x54,
	0x48, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x2a, 0x91, 0x01, 0x0a, 0x0e, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x16,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x49, 0x46, 0x49,
	0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x49, 0x4f, 0x4c,
	0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x55, 0x53, 0x53, 0x49, 0x4e, 0x45,
	0x53, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x49, 0x53, 0x43, 0x45, 0x4c, 0x4c, 0x41, 0x4e,
	0x49, 0x4f, 0x55, 0x53, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x45, 0x4f, 0x50, 0x4c, 0x45,
	0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x44, 0x55, 0x53, 0x54, 0x52, 0x59, 0x10, 0x05,
	0x12, 0x0d, 0x0a, 0x09, 0x45, 0x4d, 0x4f, 0x54, 0x49, 0x4f, 0x4e, 0x41, 0x4c, 0x10, 0x06, 0x12,
	0x0c, 0x0a, 0x08, 0x43, 0x52, 0x49, 0x4d, 0x49, 0x4e, 0x41, 0x4c, 0x10, 0x07, 0x42, 0x35, 0x5a,
	0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6e, 0x64, 0x72,
	0x65, 0x77, 0x41, 0x6c, 0x69, 0x7a, 0x61, 0x67, 0x61, 0x2f, 0x65, 0x6f, 0x67, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6c, 0x65, 0x61, 0x64, 0x3b, 0x6c, 0x65,
	0x61, 0x64, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lead_lead_proto_rawDescOnce sync.Once
	file_proto_lead_lead_proto_rawDescData = file_proto_lead_lead_proto_rawDesc
)

func file_proto_lead_lead_proto_rawDescGZIP() []byte {
	file_proto_lead_lead_proto_rawDescOnce.Do(func() {
		file_proto_lead_lead_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lead_lead_proto_rawDescData)
	})
	return file_proto_lead_lead_proto_rawDescData
}

var file_proto_lead_lead_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_lead_lead_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_lead_lead_proto_goTypes = []interface{}{
	(LeadStatus)(0),     // 0: lead.LeadStatus
	(Classification)(0), // 1: lead.Classification
	(*Lead)(nil),        // 2: lead.Lead
	(*LeadView)(nil),    // 3: lead.LeadView
}
var file_proto_lead_lead_proto_depIdxs = []int32{
	1, // 0: lead.Lead.Classification:type_name -> lead.Classification
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_lead_lead_proto_init() }
func file_proto_lead_lead_proto_init() {
	if File_proto_lead_lead_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lead_lead_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lead_lead_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeadView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lead_lead_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_lead_lead_proto_goTypes,
		DependencyIndexes: file_proto_lead_lead_proto_depIdxs,
		EnumInfos:         file_proto_lead_lead_proto_enumTypes,
		MessageInfos:      file_proto_lead_lead_proto_msgTypes,
	}.Build()
	File_proto_lead_lead_proto = out.File
	file_proto_lead_lead_proto_rawDesc = nil
	file_proto_lead_lead_proto_goTypes = nil
	file_proto_lead_lead_proto_depIdxs = nil
}
