// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/case/case.proto

package casev1

import (
	lead "github.com/AndrewAlizaga/eog_protos/pkg/lead"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaseStatus int32

const (
	CaseStatus_UNKNOWN  CaseStatus = 0
	CaseStatus_STARTED  CaseStatus = 1
	CaseStatus_PENDING  CaseStatus = 2
	CaseStatus_FINISHED CaseStatus = 3
	CaseStatus_ABORTED  CaseStatus = 4
)

// Enum value maps for CaseStatus.
var (
	CaseStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "STARTED",
		2: "PENDING",
		3: "FINISHED",
		4: "ABORTED",
	}
	CaseStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"STARTED":  1,
		"PENDING":  2,
		"FINISHED": 3,
		"ABORTED":  4,
	}
)

func (x CaseStatus) Enum() *CaseStatus {
	p := new(CaseStatus)
	*p = x
	return p
}

func (x CaseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_case_case_proto_enumTypes[0].Descriptor()
}

func (CaseStatus) Type() protoreflect.EnumType {
	return &file_proto_case_case_proto_enumTypes[0]
}

func (x CaseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaseStatus.Descriptor instead.
func (CaseStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_case_case_proto_rawDescGZIP(), []int{0}
}

type CaseFilters int32

const (
	CaseFilters_UNKNOWN_FILTER CaseFilters = 0
	CaseFilters_VIOLENT        CaseFilters = 1
	CaseFilters_BUSSINES       CaseFilters = 2
	CaseFilters_MISCELLANIOUS  CaseFilters = 3
	CaseFilters_PEOPLE         CaseFilters = 4
	CaseFilters_INDUSTRY       CaseFilters = 5
	CaseFilters_EMOTIONAL      CaseFilters = 6
	CaseFilters_CRIMINAL       CaseFilters = 7
)

// Enum value maps for CaseFilters.
var (
	CaseFilters_name = map[int32]string{
		0: "UNKNOWN_FILTER",
		1: "VIOLENT",
		2: "BUSSINES",
		3: "MISCELLANIOUS",
		4: "PEOPLE",
		5: "INDUSTRY",
		6: "EMOTIONAL",
		7: "CRIMINAL",
	}
	CaseFilters_value = map[string]int32{
		"UNKNOWN_FILTER": 0,
		"VIOLENT":        1,
		"BUSSINES":       2,
		"MISCELLANIOUS":  3,
		"PEOPLE":         4,
		"INDUSTRY":       5,
		"EMOTIONAL":      6,
		"CRIMINAL":       7,
	}
)

func (x CaseFilters) Enum() *CaseFilters {
	p := new(CaseFilters)
	*p = x
	return p
}

func (x CaseFilters) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaseFilters) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_case_case_proto_enumTypes[1].Descriptor()
}

func (CaseFilters) Type() protoreflect.EnumType {
	return &file_proto_case_case_proto_enumTypes[1]
}

func (x CaseFilters) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaseFilters.Descriptor instead.
func (CaseFilters) EnumDescriptor() ([]byte, []int) {
	return file_proto_case_case_proto_rawDescGZIP(), []int{1}
}

// Search model.
type Case struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"status" bson:"status"
	Status CaseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=case.CaseStatus" json:"status,omitempty"`
	// @inject_tag: json:"subjectName" bson:"subjectName"
	SubjectName string `protobuf:"bytes,2,opt,name=subjectName,proto3" json:"subjectName,omitempty"`
	// @inject_tag: json:"filters" bson:"filters"
	Filters []CaseFilters `protobuf:"varint,3,rep,packed,name=filters,proto3,enum=case.CaseFilters" json:"filters,omitempty"`
	// @inject_tag: json:"urlLeads" bson:"urlLeads"
	UrlLeads []string `protobuf:"bytes,4,rep,name=urlLeads,proto3" json:"urlLeads,omitempty"`
}

func (x *Case) Reset() {
	*x = Case{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_case_case_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_case_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_proto_case_case_proto_rawDescGZIP(), []int{0}
}

func (x *Case) GetStatus() CaseStatus {
	if x != nil {
		return x.Status
	}
	return CaseStatus_UNKNOWN
}

func (x *Case) GetSubjectName() string {
	if x != nil {
		return x.SubjectName
	}
	return ""
}

func (x *Case) GetFilters() []CaseFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *Case) GetUrlLeads() []string {
	if x != nil {
		return x.UrlLeads
	}
	return nil
}

// SearchRequest model.
type CaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"case" bson:"case"
	Case *Case `protobuf:"bytes,1,opt,name=case,proto3" json:"case,omitempty"`
	// @inject_tag: json:"case_leads" bson:"case_leads"
	CaseLeads []*lead.Lead `protobuf:"bytes,2,rep,name=caseLeads,proto3" json:"caseLeads,omitempty"`
}

func (x *CaseResponse) Reset() {
	*x = CaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_case_case_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseResponse) ProtoMessage() {}

func (x *CaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_case_case_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseResponse.ProtoReflect.Descriptor instead.
func (*CaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_case_case_proto_rawDescGZIP(), []int{1}
}

func (x *CaseResponse) GetCase() *Case {
	if x != nil {
		return x.Case
	}
	return nil
}

func (x *CaseResponse) GetCaseLeads() []*lead.Lead {
	if x != nil {
		return x.CaseLeads
	}
	return nil
}

var File_proto_case_case_proto protoreflect.FileDescriptor

var file_proto_case_case_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x73, 0x65, 0x2f, 0x63, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x61, 0x73, 0x65, 0x1a, 0x15, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x65, 0x61, 0x64, 0x2f, 0x6c, 0x65, 0x61, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x65, 0x12, 0x28, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x63, 0x61, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x61, 0x73,
	0x65, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x4c, 0x65, 0x61,
	0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x75, 0x72, 0x6c, 0x4c, 0x65, 0x61,
	0x64, 0x73, 0x22, 0x58, 0x0a, 0x0c, 0x43, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x52, 0x04, 0x63, 0x61,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x63, 0x61, 0x73, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x2e, 0x4c, 0x65, 0x61,
	0x64, 0x52, 0x09, 0x63, 0x61, 0x73, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x73, 0x2a, 0x4e, 0x0a, 0x0a,
	0x43, 0x61, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x0b, 0x0a, 0x07, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x04, 0x2a, 0x86, 0x01, 0x0a,
	0x0b, 0x43, 0x61, 0x73, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x0e,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x56, 0x49, 0x4f, 0x4c, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x42, 0x55, 0x53, 0x53, 0x49, 0x4e, 0x45, 0x53, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4d,
	0x49, 0x53, 0x43, 0x45, 0x4c, 0x4c, 0x41, 0x4e, 0x49, 0x4f, 0x55, 0x53, 0x10, 0x03, 0x12, 0x0a,
	0x0a, 0x06, 0x50, 0x45, 0x4f, 0x50, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e,
	0x44, 0x55, 0x53, 0x54, 0x52, 0x59, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x4d, 0x4f, 0x54,
	0x49, 0x4f, 0x4e, 0x41, 0x4c, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x52, 0x49, 0x4d, 0x49,
	0x4e, 0x41, 0x4c, 0x10, 0x07, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6e, 0x64, 0x72, 0x65, 0x77, 0x41, 0x6c, 0x69, 0x7a, 0x61, 0x67,
	0x61, 0x2f, 0x65, 0x6f, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x63, 0x61, 0x73, 0x65, 0x3b, 0x63, 0x61, 0x73, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_case_case_proto_rawDescOnce sync.Once
	file_proto_case_case_proto_rawDescData = file_proto_case_case_proto_rawDesc
)

func file_proto_case_case_proto_rawDescGZIP() []byte {
	file_proto_case_case_proto_rawDescOnce.Do(func() {
		file_proto_case_case_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_case_case_proto_rawDescData)
	})
	return file_proto_case_case_proto_rawDescData
}

var file_proto_case_case_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_case_case_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_case_case_proto_goTypes = []interface{}{
	(CaseStatus)(0),      // 0: case.CaseStatus
	(CaseFilters)(0),     // 1: case.CaseFilters
	(*Case)(nil),         // 2: case.Case
	(*CaseResponse)(nil), // 3: case.CaseResponse
	(*lead.Lead)(nil),    // 4: lead.Lead
}
var file_proto_case_case_proto_depIdxs = []int32{
	0, // 0: case.Case.status:type_name -> case.CaseStatus
	1, // 1: case.Case.filters:type_name -> case.CaseFilters
	2, // 2: case.CaseResponse.case:type_name -> case.Case
	4, // 3: case.CaseResponse.caseLeads:type_name -> lead.Lead
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_case_case_proto_init() }
func file_proto_case_case_proto_init() {
	if File_proto_case_case_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_case_case_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Case); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_case_case_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_case_case_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_case_case_proto_goTypes,
		DependencyIndexes: file_proto_case_case_proto_depIdxs,
		EnumInfos:         file_proto_case_case_proto_enumTypes,
		MessageInfos:      file_proto_case_case_proto_msgTypes,
	}.Build()
	File_proto_case_case_proto = out.File
	file_proto_case_case_proto_rawDesc = nil
	file_proto_case_case_proto_goTypes = nil
	file_proto_case_case_proto_depIdxs = nil
}
